export const CURRENCY_CATEGORIES = {
  major: [
    {
      symbol: 'EUR/USD',
      code: 'EURUSD',
      name: 'Euro / US Dollar',
      group: 'EUR / US',
    },
    {
      symbol: 'GBP/USD',
      code: 'GBPUSD',
      name: 'British Pound / US Dollar',
      group: 'GB / US',
    },
    {
      symbol: 'USD/JPY',
      code: 'USDJPY',
      name: 'US Dollar / Japanese Yen',
      group: 'US / JP',
    },
    {
      symbol: 'USD/CHF',
      code: 'USDCHF',
      name: 'US Dollar / Swiss Franc',
      group: 'US / CH',
    },
    {
      symbol: 'AUD/USD',
      code: 'AUDUSD',
      name: 'Australian Dollar / US Dollar',
      group: 'AU / US',
    },
    {
      symbol: 'USD/CAD',
      code: 'USDCAD',
      name: 'US Dollar / Canadian Dollar',
      group: 'US / CA',
    },
    {
      symbol: 'NZD/USD',
      code: 'NZDUSD',
      name: 'New Zealand Dollar / US Dollar',
      group: 'NZ / US',
    },
  ],
  minor: [
    {
      symbol: 'EUR/GBP',
      code: 'EURGBP',
      name: 'Euro / British Pound',
      group: 'EUR / GB',
    },
    {
      symbol: 'EUR/JPY',
      code: 'EURJPY',
      name: 'Euro / Japanese Yen',
      group: 'EUR / JP',
    },
    {
      symbol: 'EUR/CHF',
      code: 'EURCHF',
      name: 'Euro / Swiss Franc',
      group: 'EUR / CH',
    },
    {
      symbol: 'EUR/AUD',
      code: 'EURAUD',
      name: 'Euro / Australian Dollar',
      group: 'EUR / AU',
    },
    {
      symbol: 'EUR/CAD',
      code: 'EURCAD',
      name: 'Euro / Canadian Dollar',
      group: 'EUR / CA',
    },
    {
      symbol: 'EUR/NZD',
      code: 'EURNZD',
      name: 'Euro / New Zealand Dollar',
      group: 'EUR / NZ',
    },
    {
      symbol: 'GBP/JPY',
      code: 'GBPJPY',
      name: 'British Pound / Japanese Yen',
      group: 'GB / JP',
    },
    {
      symbol: 'GBP/CHF',
      code: 'GBPCHF',
      name: 'British Pound / Swiss Franc',
      group: 'GB / CH',
    },
    {
      symbol: 'GBP/AUD',
      code: 'GBPAUD',
      name: 'British Pound / Australian Dollar',
      group: 'GB / AU',
    },
    {
      symbol: 'AUD/JPY',
      code: 'AUDJPY',
      name: 'Australian Dollar / Japanese Yen',
      group: 'AU / JP',
    },
    {
      symbol: 'AUD/CAD',
      code: 'AUDCAD',
      name: 'Australian Dollar / Canadian Dollar',
      group: 'AU / CA',
    },
    {
      symbol: 'AUD/NZD',
      code: 'AUDNZD',
      name: 'Australian Dollar / New Zealand Dollar',
      group: 'AU / NZ',
    },
    {
      symbol: 'CAD/JPY',
      code: 'CADJPY',
      name: 'Canadian Dollar / Japanese Yen',
      group: 'CA / JP',
    },
    {
      symbol: 'CHF/JPY',
      code: 'CHFJPY',
      name: 'Swiss Franc / Japanese Yen',
      group: 'CH / JP',
    },
    {
      symbol: 'NZD/JPY',
      code: 'NZDJPY',
      name: 'New Zealand Dollar / Japanese Yen',
      group: 'NZ / JP',
    },
  ],
  exotic: [
    {
      symbol: 'USD/SGD',
      code: 'USDSGD',
      name: 'US Dollar / Singapore Dollar',
      group: 'US / SG',
    },
    {
      symbol: 'USD/HKD',
      code: 'USDHKD',
      name: 'US Dollar / Hong Kong Dollar',
      group: 'US / HK',
    },
    {
      symbol: 'USD/SEK',
      code: 'USDSEK',
      name: 'US Dollar / Swedish Krona',
      group: 'US / SE',
    },
    {
      symbol: 'USD/NOK',
      code: 'USDNOK',
      name: 'US Dollar / Norwegian Krone',
      group: 'US / NO',
    },
    {
      symbol: 'USD/DKK',
      code: 'USDDKK',
      name: 'US Dollar / Danish Krone',
      group: 'US / DK',
    },
    {
      symbol: 'USD/ZAR',
      code: 'USDZAR',
      name: 'US Dollar / South African Rand',
      group: 'US / ZA',
    },
    {
      symbol: 'USD/MXN',
      code: 'USDMXN',
      name: 'US Dollar / Mexican Peso',
      group: 'US / MX',
    },
    {
      symbol: 'USD/TRY',
      code: 'USDTRY',
      name: 'US Dollar / Turkish Lira',
      group: 'US / TR',
    },
    {
      symbol: 'USD/PLN',
      code: 'USDPLN',
      name: 'US Dollar / Polish Zloty',
      group: 'US / PL',
    },
    {
      symbol: 'EUR/TRY',
      code: 'EURTRY',
      name: 'Euro / Turkish Lira',
      group: 'EUR / TR',
    },
    {
      symbol: 'EUR/SEK',
      code: 'EURSEK',
      name: 'Euro / Swedish Krona',
      group: 'EUR / SE',
    },
    {
      symbol: 'EUR/NOK',
      code: 'EURNOK',
      name: 'Euro / Norwegian Krone',
      group: 'EUR / NO',
    },
    {
      symbol: 'EUR/DKK',
      code: 'EURDKK',
      name: 'Euro / Danish Krone',
      group: 'EUR / DK',
    },
  ],
  metals: [
    {
      symbol: 'XAU/USD',
      code: 'XAUUSD',
      name: 'Gold / US Dollar',
      group: 'XAU / US',
    },
    {
      symbol: 'XAG/USD',
      code: 'XAGUSD',
      name: 'Silver / US Dollar',
      group: 'XAG / US',
    },
    {
      symbol: 'XAU/EUR',
      code: 'XAUEUR',
      name: 'Gold / Euro',
      group: 'XAU / EU',
    },
    {
      symbol: 'XAU/GBP',
      code: 'XAUGBP',
      name: 'Gold / British Pound',
      group: 'XAU / GB',
    },
    {
      symbol: 'XAU/JPY',
      code: 'XAUJPY',
      name: 'Gold / Japanese Yen',
      group: 'XAU / JP',
    },
    {
      symbol: 'XAU/AUD',
      code: 'XAUAUD',
      name: 'Gold / Australian Dollar',
      group: 'XAU / AU',
    },
    {
      symbol: 'XAU/CAD',
      code: 'XAUCAD',
      name: 'Gold / Canadian Dollar',
      group: 'XAU / CA',
    },
    {
      symbol: 'XAG/EUR',
      code: 'XAGEUR',
      name: 'Silver / Euro',
      group: 'XAG / EU',
    },
    {
      symbol: 'XAG/GBP',
      code: 'XAGGBP',
      name: 'Silver / British Pound',
      group: 'XAG / GB',
    },
  ],
}

export const PIP_VALUES = {
  // Major pairs
  'EUR/USD': 10,
  'GBP/USD': 10,
  'USD/JPY': 1000,
  'USD/CHF': 10,
  'AUD/USD': 10,
  'USD/CAD': 10,
  'NZD/USD': 10,
  // Minor pairs
  'EUR/GBP': 10,
  'EUR/JPY': 1000,
  'EUR/CHF': 10,
  'EUR/AUD': 10,
  'EUR/CAD': 10,
  'EUR/NZD': 10,
  'GBP/JPY': 1000,
  'GBP/CHF': 10,
  'GBP/AUD': 10,
  'AUD/JPY': 1000,
  'AUD/CAD': 10,
  'AUD/NZD': 10,
  'CAD/JPY': 1000,
  'CHF/JPY': 1000,
  'NZD/JPY': 1000,
  // Exotic pairs
  'USD/SGD': 10,
  'USD/HKD': 10,
  'USD/SEK': 10,
  'USD/NOK': 10,
  'USD/DKK': 10,
  'USD/ZAR': 10,
  'USD/MXN': 10,
  'USD/TRY': 10,
  'USD/PLN': 10,
  'EUR/TRY': 10,
  'EUR/SEK': 10,
  'EUR/NOK': 10,
  'EUR/DKK': 10,
  // Metals
  'XAU/USD': 10,
  'XAG/USD': 10,
  'XAU/EUR': 10,
  'XAU/GBP': 10,
  'XAU/JPY': 1000,
  'XAU/AUD': 10,
  'XAU/CAD': 10,
  'XAG/EUR': 10,
  'XAG/GBP': 10,
}
